network:
  ethernets:
    {{ item.key }}:
      match:
        macaddress: {{ item.value.macAddress }}
      set-name: {{ item.key }}
      addresses: {{ item.value.ipAddresses }}
      accept-ra: false
      optional: true
  version: 2

