network:
  ethernets:
    {{ item.networkName }}:
      match:
        macaddress: {{ item.macAddress }}
      set-name: {{ item.networkName }}
      addresses: {{ item.ipAddresses }}
      accept-ra: false
      optional: true
  version: 2

