---
- name: Install ISC DHCP server
  tags: dhcpserver
  apt:
    name: "isc-dhcp-server"

- name: Create dhcp config directories
  tags: dhcpserver
  file:
    dest: "/etc/dhcp/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
   - dhcpd.conf.d
   - dhcpd6.conf.d

- name: Configure dhcp interfaces
  tags: dhcpserver
  template:
    src: netplan/dhcpInterfaces.yaml
    dest: "/etc/netplan/{{ item.networkName }}.yaml"
  with_items:
    - "{{ networks }}"
  when: item.networkName != "" and item.interfaceAddresses != ""

- name: Set per network dhcp v4 config
  tags: dhcpserver
  template:
    src: dhcp/network4.conf
    dest: "/etc/dhcp/dhcpd.conf.d/{{ item.networkName }}.conf"
  notify: restart isc-dhcp-server
  with_items:
    - "{{ networks }}"
  when: item.network4 is defined and item.network4 != ""

- name: Set per network dhcp v6 config
  tags: dhcpserver
  template:
    src: dhcp/network6.conf
    dest: "/etc/dhcp/dhcpd6.conf.d/{{ item.networkName }}.conf"
  notify: restart isc-dhcp-server
  with_items:
    - "{{ networks }}"
  when: item.network6 is defined and item.network6 != ""

- name: Set ISC DHCP server config
  tags: dhcpserver
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  notify: restart isc-dhcp-server
  with_items:
    - default/isc-dhcp-server
    - dhcp/dhcpd.conf
    - dhcp/dhcpd6.conf

